### ISSUE TITLE
ReviewServiceTest 에러 발생

### ISSUE THREAD

**Issue by yangwon-park** [yangwon-park/our_neighborhood#232]
**Describe the bug**
ReviewServiceTest 94번째 코드 getUploadFileName() 못 받아옴

**Expected behavior**
review.getFileList()에서 getUploadFileName()을 가져오므로 발생함
review 이미지 여러장으로 받아오는 방향으로 수정 후 발생한 에러인듯

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by hansungmoon** [comment]
reviewServiceTest에 saveReview 에러수정 완료
