### ISSUE TITLE
해쉬태그 동록창 버그

### ISSUE THREAD

**Issue by hansungmoon** [yangwon-park/our_neighborhood#235]
Describe the bug
가게페이지 해쉬태그 등록 창에서 엔터키를 누르면 등록되지 않고 창이 꺼지면서 새로고침된다.

Expected behavior
원인 발견 못함

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Additional context

**Screenshots**
![image](https://user-images.githubusercontent.com/98951034/204469118-ab75a81f-50cb-4854-9a6a-626d7370f168.png)

**Comment by yangwon-park** [comment]
엔터키 입력 시 이벤츠 추가하여 해결 완료.
