### ISSUE TITLE
가게 삭제시 null에러

### ISSUE THREAD

**Issue by hansungmoon** [yangwon-park/our_neighborhood#275]
Describe the bug
가게 삭제시 대표사진이 없으면 storeService에 파일삭제에서 nullpointException이 발생한다.

Expected behavior
가게 대표사진유무를 확인후 삭제하면 해결가능

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Additional context

**Comment by yangwon-park** [comment]
S3 버킷에 존재하는 대표사진 삭제시 함께 처리 못하여 버그 발생. 해결 완료
