### ISSUE TITLE
해쉬태그 등록시 알림 오류

### ISSUE THREAD

**Issue by hansungmoon** [yangwon-park/our_neighborhood#276]
Describe the bug
해쉬태그 등록을하면 alert알림으로 "카테고리 등록이 완료되었습니다. " 이 뜬다.

Expected behavior
alert부분 메세지 수정 필요함

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Additional context

Screenshots
![image](https://user-images.githubusercontent.com/98951034/206839433-a195e322-76ae-4e12-bc97-91a31c52f50b.png)

**Comment by yangwon-park** [comment]
js 파일 alert 메세지 수정 완료.
