### ISSUE TITLE
리뷰가 불러와지지 않음

### ISSUE THREAD

**Issue by yangwon-park** [yangwon-park/our_neighborhood#294]
**Describe the bug**
기존에 등록돼있던 리뷰가 불러와지지 않음.

**To Reproduce**
1. 로그인
2. 리뷰가 존재하는 매장에 접근
3. 기존 리뷰가 없는 버그 확인

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by hansungmoon** [comment]
회원에 프로필 사진을 추가하면서 기존에 사진이 없는 회원들이 작성한 리뷰가 불러와지지 않음
새로 작성된 리뷰는 불러와짐 기존 회원에 사진을 추가해서 해결
