### ISSUE TITLE
API 로그인 기능 동작 안 함

### ISSUE THREAD

**Issue by yangwon-park** [yangwon-park/our_neighborhood#309]
**Describe the bug**
API 로그인 기능 권한 문제로 인하여 현재 동작하지 않음.

**To Reproduce**
1. 로그인 화면으로 이동
2. 3개의 API 로그인 중 아무거나 클릭
3. 400 ERROR 확인

**Expected behavior**
해당 API 권한 설정을 다시 손봐야할 것 같음

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by hansungmoon** [comment]
yml과 카카오 네이버 구글 redirectUrl 허용으로 해결
