### ISSUE TITLE
프로필 사진 박스를 원형으로 바꿔달라는 요청이 있음

### ISSUE THREAD

**Issue by yangwon-park** [yangwon-park/our_neighborhood#317]
**추가하고자 하는 기능에 대하여 상세하게 기술 **
현재 정사각형인 프로필 사진 박스를 원형으로 변경하자는 요청

**Comment by hansungmoon** [comment]
![image](https://user-images.githubusercontent.com/98951034/208600487-445ca321-a900-4e4d-af9a-a77ae810cdfe.png)
![image](https://user-images.githubusercontent.com/98951034/208600532-dd63eb19-b382-4d6c-b00b-8f82ce5ff248.png)
css수정으로 완료
