### ISSUE TITLE
가게에 대표사진을 안넣은경우 삭제시 NullpointException

### ISSUE THREAD

**Issue by hansungmoon** [yangwon-park/our_neighborhood#320]
대표사진을 넣지않은채로 가게 정보수정에서 삭제를 하면 NullPointerException이 발생함 

To Reproduce

가게를 새로 등록
대표사진을 등록하지 않은채로 정보수정에서 삭제
로딩이 계속되며 콘솔에 Nullpoint예외 발생

Expected behavior
StoreService의 delete 메서드에서 store.getFile().getStoredFileName()을 실행하는데 store.getFile을 null체크하는 방법으로 전환하여야 한다.

![image](https://user-images.githubusercontent.com/98951034/208654713-61e40595-11b1-4764-8960-e12ff6f95660.png)

Desktop (please complete the following information):

OS: Windwos 10
Browser: Chrome

**Comment by yangwon-park** [comment]
store.getFile().getOriginalName()의 null 체크 여부를 getFile()체크 레벨에서 처리하여 해결 완료
