### ISSUE TITLE
폰트 바꾼후 비밀번호 보이지 않음

### ISSUE THREAD

**Issue by hansungmoon** [yangwon-park/our_neighborhood#324]
폰트를 변경한후 <input type="password">가 들어가는 모든 비밀번호 input에 점이 보이지 않음

To Reproduce
로그인 창에 들어간다
비밀번호를 입력한다
비밀번호가 입력이 되나 점으로 떠야하는 입력이 보이지 않는다

Expected behavior
type="password"시 보이게 폰트를 수정해야 한다.

![image](https://user-images.githubusercontent.com/98951034/208877506-3c0a4a18-5be7-46c7-b8d3-adacf26da084.png)

Desktop (please complete the following information):

OS: Windwos 10
Browser: Chrome

**Comment by yangwon-park** [comment]
Cafe24Ssurround 폰트가 해당 특수문자를 표현하지 못하여 password 부분의 폰트를 s-core로 변경
